import { Delivery as PrismaDelivery } from '@prisma/client';
import { Delivery } from '../domain/delivery.entity';
import { VehicleType } from '@/core/domain/enums';

export class DeliveryMapper {
  public static toDomain(raw: PrismaDelivery): Delivery {
    const deliveryResult = Delivery.create(
      {
        order_id: raw.order_id,
        courier_id: raw.courier_id,
        status_id: raw.status_id,
        assigned_at: raw.assigned_at,
        // The following fields are not in the Prisma schema, so we need to provide default values
        vehicle_type: VehicleType.MOTORCYCLE,
        pickup_at: new Date(),
        dropoff_at: new Date(),
        distance_meters: 0,
        eta_seconds: 0,
        failure_reason: '',
      },
      raw.id,
    );

    if (!deliveryResult.success) {
      throw new Error(`Failed to map raw data to Delivery entity: ${deliveryResult.error.message}`);
    }
    return deliveryResult.value;
  }

  public static toPersistence(delivery: Delivery) {
    const props = delivery.props;
    return {
      id: delivery.id,
      order_id: props.order_id,
      courier_id: props.courier_id,
      status_id: props.status_id,
      assigned_at: props.assigned_at,
      delivered_at: props.dropoff_at,
      expected_delivery_date: props.pickup_at,
      tracking_number: '', // This will be generated by the use case
    };
  }
}
